// Auto-generated by scripts/lib/scaffold-component.mjs.
// Do not edit by hand — regenerated on every approve/discard action.

import type { ComponentType } from "react"

export type Draft = { slug: string; componentName: string; component: ComponentType }

export const drafts: Draft[] = []
